# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8195286320107982a3818cd25e9e004ebc320b2def8efcda936e1c072a5186c362e73adf43c82b61bdf4923186c1e80c094ac45f213c86fc821db4167aa98c5

test:
  secret_key_base: 38135875272d1430fcedde6d7fb8118d276b71c44a49763bdae1b66776d41579419cc987eccf5d8b0aca1988dcb188c97f58ba1121d64593928255eeee3feacf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
